version: '3.8'
name: 'elasticsearch-cluster-biaf'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g' # Heap ajustado para 2 GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - es-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - es-network

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - es-network
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '15672:15672' # Porta para acessar a interface de gerenciamento
      - '5672:5672' # Porta para a comunicação com o RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin # Usuário padrão
      - RABBITMQ_DEFAULT_PASS=admin # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistência dos dados do RabbitMQ

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  es-network:
    driver: bridge
